port: "8000"

db:
  username: "postgres"
  password: "2426101527"
  host: "127.0.0.1"
  port: "5432"
  dbname: "L0WB-test"
  sslmode: "disable"

natStreaming:
  clusterId: "test-cluster"
  clientId: "test-client"
  natsURL: "nats://localhost:4222"